//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BedsideMonitoring.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BedsideMonitoring.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Rate,Breathing Rate,Blood Pressure Systolic,Blood Pressure Diastolic,Temperature
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///80,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bed_1 {
            get {
                return ResourceManager.GetString("Bed_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Rate,Breathing Rate,Blood Pressure Systolic,Blood Pressure Diastolic,Temperature
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bed_2 {
            get {
                return ResourceManager.GetString("Bed_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Rate,Breathing Rate,Blood Pressure Systolic,Blood Pressure Diastolic,Temperature
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bed_3 {
            get {
                return ResourceManager.GetString("Bed_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Rate,Breathing Rate,Blood Pressure Systolic,Blood Pressure Diastolic,Temperature
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bed_4 {
            get {
                return ResourceManager.GetString("Bed_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Rate,Breathing Rate,Blood Pressure Systolic,Blood Pressure Diastolic,Temperature
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bed_5 {
            get {
                return ResourceManager.GetString("Bed_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Rate,Breathing Rate,Blood Pressure Systolic,Blood Pressure Diastolic,Temperature
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bed_6 {
            get {
                return ResourceManager.GetString("Bed_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Rate,Breathing Rate,Blood Pressure Systolic,Blood Pressure Diastolic,Temperature
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bed_7 {
            get {
                return ResourceManager.GetString("Bed_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Rate,Breathing Rate,Blood Pressure Systolic,Blood Pressure Diastolic,Temperature
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102,72,38
        ///60,20,100,70,37.7
        ///62,21,102 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bed_8 {
            get {
                return ResourceManager.GetString("Bed_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Mutable {
            get {
                return ResourceManager.GetStream("Mutable", resourceCulture);
            }
        }
    }
}
